

export const beadColors = {
    basic: [
    { name: '红色', hex: '#F44336', category: 'basic' },
    { name: '粉色', hex: '#E91E63', category: 'basic' },
    { name: '紫色', hex: '#9C27B0', category: 'basic' },
    { name: '深紫', hex: '#673AB7', category: 'basic' },
    { name: '蓝色', hex: '#3F51B5', category: 'basic' },
    { name: '天蓝', hex: '#2196F3', category: 'basic' },
    { name: '青色', hex: '#03A9F4', category: 'basic' },
    { name: '湖蓝', hex: '#00BCD4', category: 'basic' },
    { name: '绿色', hex: '#009688', category: 'basic' },
    { name: '草绿', hex: '#4CAF50', category: 'basic' },
    { name: '黄绿', hex: '#8BC34A', category: 'basic' },
    { name: '柠檬', hex: '#CDDC39', category: 'basic' },
    { name: '黄色', hex: '#FFEB3B', category: 'basic' },
    { name: '橙色', hex: '#FFC107', category: 'basic' },
    { name: '橘色', hex: '#FF9800', category: 'basic' },
    { name: '深橙', hex: '#FF5722', category: 'basic' },
  ],
  // A色系（暖黄/橙色系）
  A: [
    { name: 'A1', hex: '#faf5cd', category: 'A' },
    { name: 'A2', hex: '#fcfed6', category: 'A' },
    { name: 'A3', hex: '#fcff92', category: 'A' },
    { name: 'A4', hex: '#f7ec5c', category: 'A' },
    { name: 'A5', hex: '#f0d83a', category: 'A' },
    { name: 'A6', hex: '#fda951', category: 'A' },
    { name: 'A7', hex: '#fa8c4f', category: 'A' },
    { name: 'A8', hex: '#fbda4d', category: 'A' },
    { name: 'A9', hex: '#f79d5f', category: 'A' },
    { name: 'A10', hex: '#f47e38', category: 'A' },
    { name: 'A11', hex: '#fedb99', category: 'A' },
    { name: 'A12', hex: '#fda276', category: 'A' },
    { name: 'A13', hex: '#fec667', category: 'A' },
    { name: 'A14', hex: '#f75842', category: 'A' },
    { name: 'A15', hex: '#fbf65e', category: 'A' },
    { name: 'A16', hex: '#feff97', category: 'A' },
    { name: 'A17', hex: '#fde173', category: 'A' },
    { name: 'A18', hex: '#fcbf80', category: 'A' },
    { name: 'A19', hex: '#fd7e77', category: 'A' },
    { name: 'A20', hex: '#f9d666', category: 'A' },
    { name: 'A21', hex: '#fae393', category: 'A' },
    { name: 'A22', hex: '#edf878', category: 'A' },
    { name: 'A23', hex: '#e4c8ba', category: 'A' },
    { name: 'A24', hex: '#f3f6a9', category: 'A' },
    { name: 'A25', hex: '#fdf785', category: 'A' },
    { name: 'A26', hex: '#ffc734', category: 'A' }
  ],

  // B色系（绿色/自然色系）
  B: [
    { name: 'B1', hex: '#dff13b', category: 'B' },
    { name: 'B2', hex: '#64f343', category: 'B' },
    { name: 'B3', hex: '#a1f586', category: 'B' },
    { name: 'B4', hex: '#5fdf34', category: 'B' },
    { name: 'B5', hex: '#39e158', category: 'B' },
    { name: 'B6', hex: '#64e0a4', category: 'B' },
    { name: 'B7', hex: '#3eae7c', category: 'B' },
    { name: 'B8', hex: '#1d9b54', category: 'B' },
    { name: 'B9', hex: '#2a5037', category: 'B' },
    { name: 'B10', hex: '#9ad1ba', category: 'B' },
    { name: 'B11', hex: '#627032', category: 'B' },
    { name: 'B12', hex: '#1a6e3d', category: 'B' },
    { name: 'B13', hex: '#c8e87d', category: 'B' },
    { name: 'B14', hex: '#abe84f', category: 'B' },
    { name: 'B15', hex: '#305335', category: 'B' },
    { name: 'B16', hex: '#c0ed9c', category: 'B' },
    { name: 'B17', hex: '#9eb33e', category: 'B' },
    { name: 'B18', hex: '#e6ed4f', category: 'B' },
    { name: 'B19', hex: '#26b78e', category: 'B' },
    { name: 'B20', hex: '#cbeccf', category: 'B' },
    { name: 'B21', hex: '#18616a', category: 'B' },
    { name: 'B22', hex: '#0a4241', category: 'B' },
    { name: 'B23', hex: '#343b1a', category: 'B' },
    { name: 'B24', hex: '#e8faa6', category: 'B' },
    { name: 'B25', hex: '#4e846d', category: 'B' },
    { name: 'B26', hex: '#907c35', category: 'B' },
    { name: 'B27', hex: '#d0e0af', category: 'B' },
    { name: 'B28', hex: '#9ee5bb', category: 'B' },
    { name: 'B29', hex: '#c6df5f', category: 'B' },
    { name: 'B30', hex: '#e3fbb1', category: 'B' },
    { name: 'B31', hex: '#b4e691', category: 'B' },
    { name: 'B32', hex: '#92ad60', category: 'B' }
  ],

  // C色系（蓝色/青色系）
  C: [
    { name: 'C1', hex: '#f0fee4', category: 'C' },
    { name: 'C2', hex: '#abf8fe', category: 'C' },
    { name: 'C3', hex: '#a2e0f7', category: 'C' },
    { name: 'C4', hex: '#44cdfb', category: 'C' },
    { name: 'C5', hex: '#06aadf', category: 'C' },
    { name: 'C6', hex: '#54a7e9', category: 'C' },
    { name: 'C7', hex: '#3977ca', category: 'C' },
    { name: 'C8', hex: '#0f52bd', category: 'C' },
    { name: 'C9', hex: '#3349c3', category: 'C' },
    { name: 'C10', hex: '#3cbce3', category: 'C' },
    { name: 'C11', hex: '#2aded3', category: 'C' },
    { name: 'C12', hex: '#1e334e', category: 'C' },
    { name: 'C13', hex: '#cde7fe', category: 'C' },
    { name: 'C14', hex: '#d5fcf7', category: 'C' },
    { name: 'C15', hex: '#21c5c4', category: 'C' },
    { name: 'C16', hex: '#1858a2', category: 'C' },
    { name: 'C17', hex: '#02d1f3', category: 'C' },
    { name: 'C18', hex: '#213244', category: 'C' },
    { name: 'C19', hex: '#18869d', category: 'C' },
    { name: 'C20', hex: '#1a70a9', category: 'C' },
    { name: 'C21', hex: '#bcddfc', category: 'C' },
    { name: 'C22', hex: '#6bb1bb', category: 'C' },
    { name: 'C23', hex: '#c8e2fd', category: 'C' },
    { name: 'C24', hex: '#7ec5f9', category: 'C' },
    { name: 'C25', hex: '#a9e8e0', category: 'C' },
    { name: 'C26', hex: '#42adcf', category: 'C' },
    { name: 'C27', hex: '#d0def9', category: 'C' },
    { name: 'C28', hex: '#bdcee8', category: 'C' },
    { name: 'C29', hex: '#364a89', category: 'C' }
  ],

  // D色系（紫色/蓝紫色系）
  D: [
    { name: 'D1', hex: '#acb7ef', category: 'D' },
    { name: 'D2', hex: '#868dd3', category: 'D' },
    { name: 'D3', hex: '#3554af', category: 'D' },
    { name: 'D4', hex: '#162d7b', category: 'D' },
    { name: 'D5', hex: '#b34ec6', category: 'D' },
    { name: 'D6', hex: '#b37bdc', category: 'D' },
    { name: 'D7', hex: '#8758a9', category: 'D' },
    { name: 'D8', hex: '#e3d2fe', category: 'D' },
    { name: 'D9', hex: '#d5b9f4', category: 'D' },
    { name: 'D10', hex: '#301a49', category: 'D' },
    { name: 'D11', hex: '#beb9e2', category: 'D' },
    { name: 'D12', hex: '#dc99ce', category: 'D' },
    { name: 'D13', hex: '#b5038d', category: 'D' },
    { name: 'D14', hex: '#862993', category: 'D' },
    { name: 'D15', hex: '#2f1f8c', category: 'D' },
    { name: 'D16', hex: '#e2e4f0', category: 'D' },
    { name: 'D17', hex: '#c7d3f9', category: 'D' },
    { name: 'D18', hex: '#9a64b8', category: 'D' },
    { name: 'D19', hex: '#d8c2d9', category: 'D' },
    { name: 'D20', hex: '#9a35ad', category: 'D' },
    { name: 'D21', hex: '#940595', category: 'D' },
    { name: 'D22', hex: '#38389a', category: 'D' },
    { name: 'D23', hex: '#eadbf8', category: 'D' },
    { name: 'D24', hex: '#768ae1', category: 'D' },
    { name: 'D25', hex: '#4950c2', category: 'D' },
    { name: 'D26', hex: '#d6c6eb', category: 'D' }
  ],

  // E色系（粉色/红色系）
  E: [
    { name: 'E1', hex: '#f6d4cb', category: 'E' },
    { name: 'E2', hex: '#fcc1dd', category: 'E' },
    { name: 'E3', hex: '#f6bde8', category: 'E' },
    { name: 'E4', hex: '#e8649e', category: 'E' },
    { name: 'E5', hex: '#f0569f', category: 'E' },
    { name: 'E6', hex: '#eb4172', category: 'E' },
    { name: 'E7', hex: '#c53674', category: 'E' },
    { name: 'E8', hex: '#fddbe9', category: 'E' },
    { name: 'E9', hex: '#e376c7', category: 'E' },
    { name: 'E10', hex: '#d13b95', category: 'E' },
    { name: 'E11', hex: '#f7dad4', category: 'E' },
    { name: 'E12', hex: '#f693bf', category: 'E' },
    { name: 'E13', hex: '#b5026a', category: 'E' },
    { name: 'E14', hex: '#fad4bf', category: 'E' },
    { name: 'E15', hex: '#f5c9ca', category: 'E' },
    { name: 'E16', hex: '#fbf4ec', category: 'E' },
    { name: 'E17', hex: '#f7e3ec', category: 'E' },
    { name: 'E18', hex: '#f9c8db', category: 'E' },
    { name: 'E19', hex: '#f6bbd1', category: 'E' },
    { name: 'E20', hex: '#d7c6ce', category: 'E' },
    { name: 'E21', hex: '#c09da4', category: 'E' },
    { name: 'E22', hex: '#b38c9f', category: 'E' },
    { name: 'E23', hex: '#937d8a', category: 'E' },
    { name: 'E24', hex: '#debee5', category: 'E' }
  ],

  // F色系（红色/橙色系）
  F: [
    { name: 'F1', hex: '#fe9381', category: 'F' },
    { name: 'F2', hex: '#f63d4b', category: 'F' },
    { name: 'F3', hex: '#ee4e3e', category: 'F' },
    { name: 'F4', hex: '#fb2a40', category: 'F' },
    { name: 'F5', hex: '#e10328', category: 'F' },
    { name: 'F6', hex: '#913635', category: 'F' },
    { name: 'F7', hex: '#911932', category: 'F' },
    { name: 'F8', hex: '#bb0126', category: 'F' },
    { name: 'F9', hex: '#e0677a', category: 'F' },
    { name: 'F10', hex: '#874628', category: 'F' },
    { name: 'F11', hex: '#592323', category: 'F' },
    { name: 'F12', hex: '#f3536b', category: 'F' },
    { name: 'F13', hex: '#f45c45', category: 'F' },
    { name: 'F14', hex: '#fcadb2', category: 'F' },
    { name: 'F15', hex: '#d50527', category: 'F' },
    { name: 'F16', hex: '#f8c0a9', category: 'F' },
    { name: 'F17', hex: '#e89b7d', category: 'F' },
    { name: 'F18', hex: '#d07f4a', category: 'F' },
    { name: 'F19', hex: '#be454a', category: 'F' },
    { name: 'F20', hex: '#c69495', category: 'F' },
    { name: 'F21', hex: '#f2b8c6', category: 'F' },
    { name: 'F22', hex: '#f7c3d0', category: 'F' },
    { name: 'F23', hex: '#ed806c', category: 'F' },
    { name: 'F24', hex: '#e09daf', category: 'F' },
    { name: 'F25', hex: '#e84854', category: 'F' }
  ],

  // G色系（棕色/大地色系）
  G: [
    { name: 'G1', hex: '#ffe4d3', category: 'G' },
    { name: 'G2', hex: '#fcc6ac', category: 'G' },
    { name: 'G3', hex: '#f1c4a5', category: 'G' },
    { name: 'G4', hex: '#dcb387', category: 'G' },
    { name: 'G5', hex: '#e7b34e', category: 'G' },
    { name: 'G6', hex: '#e3a014', category: 'G' },
    { name: 'G7', hex: '#985c3a', category: 'G' },
    { name: 'G8', hex: '#713d2f', category: 'G' },
    { name: 'G9', hex: '#e4b685', category: 'G' },
    { name: 'G10', hex: '#da8c42', category: 'G' },
    { name: 'G11', hex: '#dac898', category: 'G' },
    { name: 'G12', hex: '#fec993', category: 'G' },
    { name: 'G13', hex: '#b2714b', category: 'G' },
    { name: 'G14', hex: '#8b684c', category: 'G' },
    { name: 'G15', hex: '#f6f8e3', category: 'G' },
    { name: 'G16', hex: '#f2d8c1', category: 'G' },
    { name: 'G17', hex: '#77544e', category: 'G' },
    { name: 'G18', hex: '#ffe3d5', category: 'G' },
    { name: 'G19', hex: '#dd7d41', category: 'G' },
    { name: 'G20', hex: '#a5452f', category: 'G' },
    { name: 'G21', hex: '#b38561', category: 'G' }
  ],

  // H色系（中性/灰度色系）
  H: [
    { name: 'H1', hex: '#ffffff', category: 'H' },
    { name: 'H2', hex: '#fbfbfb', category: 'H' },
    { name: 'H3', hex: '#b4b4b4', category: 'H' },
    { name: 'H4', hex: '#878787', category: 'H' },
    { name: 'H5', hex: '#464648', category: 'H' },
    { name: 'H6', hex: '#2c2c2c', category: 'H' },
    { name: 'H7', hex: '#010101', category: 'H' },
    { name: 'H8', hex: '#e7d6dc', category: 'H' },
    { name: 'H9', hex: '#efedee', category: 'H' },
    { name: 'H10', hex: '#ebebeb', category: 'H' },
    { name: 'H11', hex: '#cdcdcd', category: 'H' },
    { name: 'H12', hex: '#fdf6ee', category: 'H' },
    { name: 'H13', hex: '#f4edf1', category: 'H' },
    { name: 'H14', hex: '#ced7d4', category: 'H' },
    { name: 'H15', hex: '#9aa6a6', category: 'H' },
    { name: 'H16', hex: '#1b1213', category: 'H' },
    { name: 'H17', hex: '#f0eeef', category: 'H' },
    { name: 'H18', hex: '#fcfff6', category: 'H' },
    { name: 'H19', hex: '#f2eee5', category: 'H' },
    { name: 'H20', hex: '#96a09f', category: 'H' },
    { name: 'H21', hex: '#f8fbe6', category: 'H' },
    { name: 'H22', hex: '#cacad2', category: 'H' },
    { name: 'H23', hex: '#9b9c94', category: 'H' }
  ],

  // M色系（混合/中性/复古色系）
  M: [
    { name: 'M1', hex: '#bbc6b6', category: 'M' },
    { name: 'M2', hex: '#909994', category: 'M' },
    { name: 'M3', hex: '#697e81', category: 'M' },
    { name: 'M4', hex: '#e0d4bc', category: 'M' },
    { name: 'M5', hex: '#d1ccaf', category: 'M' },
    { name: 'M6', hex: '#b0aa86', category: 'M' },
    { name: 'M7', hex: '#b0a796', category: 'M' },
    { name: 'M8', hex: '#ae8082', category: 'M' },
    { name: 'M9', hex: '#a68862', category: 'M' },
    { name: 'M10', hex: '#c4b3bb', category: 'M' },
    { name: 'M11', hex: '#9d7693', category: 'M' },
    { name: 'M12', hex: '#644b51', category: 'M' },
    { name: 'M13', hex: '#c79266', category: 'M' },
    { name: 'M14', hex: '#c27563', category: 'M' },
    { name: 'M15', hex: '#747d7a', category: 'M' }
  ]
};
export default beadColors;
// 导出颜色配置
if (typeof module !== 'undefined' && module.exports) {
  module.exports = beadColors;
}